### ISSUE TITLE
Typo in Rationale - mseccfg.RLB instead of mseccfg.MML 

### ISSUE THREAD

**Issue by jahanzebkhalid-10Xe** [riscv/riscv-tee#15]
Referring to Smepmp Version 0.9.5,
On page no 6, In chapter 3 (Rationale), following note is written in non-normative section at the end 

_For adding Shared-region rules with executable privileges to share code segments
between M-mode and S/U-mode, mseccfg.RLB needs to be implemented, or else
such rules can only be added together with mseccfg.MML being set on PMP Reset.
That’s because the reserved encoding pmpcfg.RW=01 being used for Shared-region
rules is only defined when mseccfg.MML is set, and 4b prevents the adition of rules
with executable privileges on M-mode after mseccfg.MML is set unless mseccfg.MML
is also set._
where instead of:
> 4b prevents the adition of rules
> with executable privileges on M-mode after mseccfg.MML is set unless mseccfg.MML
> is also set

it should be:

> 4b prevents the adition of rules
> with executable privileges on M-mode after mseccfg.MML is set unless mseccfg.RLB
> is also set

**Comment by jahanzebkhalid-10Xe** [comment]
@mickflemm @tariqkurd-repo

**Comment by mickflemm** [comment]
Thank you ! I've updated the doc.

**Comment by jahanzebkhalid-10Xe** [comment]
> 

Great. It's my pleasure
