### ISSUE TITLE
Separating lock and m-access control bits in the ePMP

### ISSUE THREAD

**Issue by MarkHillHuawei** [riscv/riscv-tee#8]
A very useful feature of the ePMP is the ability to introduce access controls on m-mode which can be modified as the hart progresses through the different phases of boot. This phased programming helps reduce the attack surface for both physical and software attack.

In the early discussion of the m-mode access control scheme it was proposed that we had separate bits for locking and m-mode control, however, at the time there was concern over consuming another bit in the pmpcfg (currently LRWX plus two bits for A and two spare) as there could be other demands for these spare bits. We therefore settled on a single bit RLB in the mseccfg so that m-mode permissions can be updated until the bit is cleared (at which point all m-mode access controls are locked). Before we finalise the spec I think it is worth revisiting this decision, in particular:

- Although we have found the single-bit RLB useful in products with relatively simple boot sequences in more complex systems it is desirable to have a mix of locked m-mode entries and unlocked m-mode entries, with some regions going out of view and others coming it to view as the boot progresses. The RLB only allows lock-all or lock-none m-mode entries.
- Separating M and L bits is bit more intuitive and cleaner than the don't-lock-yet RLB semantics
- Separating M and L better aligns with sPMP which has an S bit which is equivalent to the M bit but without any locking semantics.

Also note that when M is clear entries are not lockable so the L bit so can potentially be used to define future sub-M controls.

**Comment by allenjbaum** [comment]
I don't understand your last comment. Why does M-mode being clear mean that an entry isn't lockable?
It seems hard to declare that if the M bit doesn't even exist yet.

**Comment by MarkHillHuawei** [comment]
Sorry Allen I should have given more background on the M=0/L=1 combination.  We have discussed this in the past and there was a general concensus that the ability to lock sub m-mode entries is not useful so the proposal here is that the L=1/M=0 combination is reserved for future use.

**Comment by mickflemm** [comment]
After further discussion during our 10/26/2021 call, and after further exploration of the use case presented at https://lists.riscv.org/g/tech-tee/topic/86574026#1039, we concluded together with Mark that the right approach for resolving this is not through ePMP but through IOPMP, for blocking access to BootROM after its execution, or by removing/hiding BootROM from the system's memory map.
